# Config file used to set up forecast analysis
# Adjusted to point to storage directory for data dictionaries
f_start: "2024-01-01T00:00:00Z" # first forecast time
f_end: "2024-12-31T23:00:00Z" # last forecast time
forecast_hours: 48 # number of hours to run forecast before re-initializing (matters for RNN and ODE baseline, has no effect on static ML models nor on climatology). Hours determined by max forecast window of HRRR
n_reps: 100 # Number of replications to train/forecast, used to estimate uncertainty in forecast accuracy metrics
train_start: "2023-01-01T00:00:00Z" # first time for training
train_end: "2023-12-31T23:00:00Z" # last time for training
val_hours: 48 # number of hours to use at end of training window (tstart, tend) to use for validation data
space_test_frac: 0.1 # Percentage of data based on location for val and test
bbox: '[27,-114.5,37,-100]' # spatial bounding box
features_list: ['Ed', 'Ew', 'solar', 'wind', 'elev', 'lon', 'lat', 'rain', 'hod', 'doy'] # inputs to ML models
baselines: ['ode', 'xgb', 'clim'] # Names of models to be run on same data for comparison. USE None if only running RNN
data_dir: "/storage/math/NSF1/hirschij/FMDA/sw_gacc/" # Directory for formatted FMDA data dictionaries
valid_path: "/storage/math/NSF1/hirschij/FMDA/valid_data/fmc_valid_sw24.csv" # Path to manually constructed table for filtered invalid data
climatology_file: "/storage/math/NSF1/hirschij/FMC_CLIMATOLOGY/climatology_sw24/climatology_sw_2024_forecasts.pkl" # name of climatology output to be used for comparison, created with src/run_climatology.py
